server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
    basedir: /logs/accesslog

spring:
  banner:
    location: classpath:/META-INF/banner.txt
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate # update valid
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/homepage?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: manager
    password: 1q2w3e4r!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    livereload:
      enabled: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 453579716491-qkva91is4o4becblnlv4ubre6e29p66d.apps.googleusercontent.com
            client-secret: 2gtzDYYt1s1gluOTeyxloXCR
          facebook:
            client-id: <your client id>
            client-secret: <your client secret>

servlet:
  multipart:
    max-file-size: 128MB
    max-request-size: 128MB


logging:
  level:
    web: INFO
    sql: INFO
    root: WARN
    tomcat: INFO

  file: logs/homepage.log
  path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"


social:
  kakao:
    client_id: 6e358349e45f9b78dd992396d4da0368

env:
  dev: local

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  health:
    elasticsearch:
      enabled: false

